version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3001:3000'
    environment:
      HOST: f502-103-5-140-147.ngrok-free.app # ngrokで生成された値に変える
      LINE_CHANNEL_SECRET: ed9a71c1d4c43b7aa85a09ee44191eba
      LINE_CHANNEL_TOKEN: HgT75MsZJtrbWJ8F93UTk1UsOizG2mEFANXFr+NoNf+0nRqM+r+/WtanHs/bDtOC+BXa9LgvHIQjUYjWSVmA0vHhgtUMmVjx20uw720DLmR8NPNMO0XXr+ACvf8ke3B3sN174N7Eph5yGSMs4qSllQdB04t89/1O/w1cDnyilFU=
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rails_line_bot # 作成したいdatabase名を記述
      MYSQL_ROOT_HOST: '%'
    volumes:
      - datadir:/var/lib/mysql
volumes:
  bundle:
  datadir: